# Generated by Django 2.0.7 on 2018-09-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'myPermissions': (('User.Students.studentsviewset.post', 'User.Students.新增'), ('User.Students.studentsviewset.delete', 'User.Students.删除'), ('User.Students.studentsviewset.put', 'User.Students.修改'), ('User.Students.studentsviewset.get', 'User.Students.查看列表'), ('User.Students.studentsviewset.get+', 'User.Students.查看详细'))},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'myPermissions': (('User.Teachers.teachersviewset.post', 'User.Teachers.新增'), ('User.Teachers.teachersviewset.delete', 'User.Teachers.删除'), ('User.Teachers.teachersviewset.put', 'User.Teachers.修改'), ('User.Teachers.teachersviewset.get', 'User.Teachers.查看列表'), ('User.Teachers.teachersviewset.get+', 'User.Teachers.查看详细'))},
        ),
    ]
